FROM python:3.11-slim

# Install core dependencies and tool backends
RUN apt update && apt install -y --no-install-recommends \
    curl wget git nmap dnsutils whois procps \
    && rm -rf /var/lib/apt/lists/*

# Install Go for Go-based tools
ENV GO_VERSION=1.21.5
RUN wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
    rm go${GO_VERSION}.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin:/root/go/bin

# Install Go-based tools (ProjectDiscovery & others)
RUN go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest && \
    go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest && \
    go install -v github.com/projectdiscovery/tlsx/cmd/tlsx@latest && \
    go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest && \
    go install -v github.com/d3mondev/puredns/v2@latest && \
    go install -v github.com/projectdiscovery/urlfinder/cmd/urlfinder@latest && \
    go install -v github.com/trickest/dsieve@latest && \
    go install -v github.com/intigriti/misconfig-mapper@latest && \
    go install -v github.com/JosueEncinar/gotator@latest && \
    go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest

# Install Python-based tools and dependencies
RUN pip install --no-cache-dir \
    fastapi uvicorn requests pyyaml \
    emailfinder \
    xnldorker \
    wafw00f \
    sqlmap \
    porch-pirate \
    postleaks-ng \
    leaksearch \
    msftrecon

# Special tools (cloning/manual install)
WORKDIR /opt
RUN git clone https://github.com/Tuhinshubhra/CMSeeK && \
    cd CMSeeK && pip install -r requirements.txt && \
    ln -s /opt/CMSeeK/cmseek.py /usr/local/bin/cmseek

RUN git clone https://github.com/six2dez/dorks_hunter && \
    ln -s /opt/dorks_hunter/dorks_hunter.py /usr/local/bin/dorks_hunter

RUN git clone https://github.com/cramppet/regulator && \
    ln -s /opt/regulator/regulator.py /usr/local/bin/regulator

RUN git clone https://github.com/JosueEncinar/AnalyticsRelationships && \
    ln -s /opt/AnalyticsRelationships/analyticsrelationships.py /usr/local/bin/analyticsrelationships

# App setup
WORKDIR /app
COPY sandbox/server.py /app/server.py
COPY tools/wrappers/ /app/tools/wrappers/

EXPOSE 8000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]