from typing import Any, Dict, List, Set, Union
import json
import csv
from pathlib import Path
from jinja2 import Environment, BaseLoader
from datetime import datetime
import logging


_MARKDOWN_TEMPLATE = """\
# 🛡️ BBH-AI Security Assessment Report
> **Target:** `{{ target }}`
> **Generated:** {{ date }}
> **Status:** Scan Completed

---

## 📊 Executive Summary

The following table summarizes the vulnerabilities identified during the multi-phase AI orchestration.

| Severity | Count | Impact Level |
|----------|-------|--------------|
| 🔴 **Critical** | {{ critical_count }} | Immediate action required |
| 🟠 **High** | {{ high_count }} | Significant security risk |
| 🟡 **Medium** | {{ medium_count }} | Moderate security risk |
| 🟢 **Low** | {{ low_count }} | Low security risk |
| ℹ️ **Info** | {{ info_count }} | Informational finding |
| **Total** | **{{ findings|length }}** | |

---

## 🔍 Tactical Findings

{% for f in findings %}
### {{ loop.index }}. {{ f.title }}
| Attribute | Detail |
|-----------|--------|
| **Severity** | {{ f.severity | upper }} |
| **Location** | `{{ f.location }}` |
| **Validation** | {{ "✅ Verified" if f.get("validated") else "⚠️ Unvalidated" }} |

#### 📝 Description
{{ f.description }}

{% if f.payload %}
#### 💉 Payload / Injection
`{{ f.payload }}`
{% endif %}

{% if f.poc %}
#### 🎥 Proof of Concept
```{{ f.poc_lang if f.poc_lang else "text" }}
{{ f.poc }}
```
{% endif %}

---
{% endfor %}

*Generated by BBH-AI: Autonomous Bug Bounty Engine*
"""


class ReportGenerator:
    """Generates professional security reports in multiple formats (MD, JSON, CSV)."""

    def __init__(self, config: Dict[str, Any], workspace: Union[str, Path], target: str = "Unknown"):
        self.config = config
        self.workspace = Path(workspace)
        self.workspace.mkdir(parents=True, exist_ok=True)
        self.target = target
        self.logger = logging.getLogger(__name__)

    def generate(self, findings: List[Dict[str, Any]]) -> Dict[str, str]:
        """Generate all configured report formats and return their file paths."""
        report_paths: Dict[str, str] = {}
        formats: List[str] = self.config.get("reporting", {}).get("formats", ["markdown", "json"])

        if "markdown" in formats:
            report_paths["markdown"] = self._generate_markdown(findings)
        if "json" in formats:
            report_paths["json"] = self._generate_json(findings)
        if "csv" in formats:
            report_paths["csv"] = self._generate_csv(findings)

        return report_paths

    def _count(self, findings: List[Dict[str, Any]], severity: str) -> int:
        """Helper to count findings by severity."""
        return sum(1 for f in findings if str(f.get("severity", "")).lower() == severity.lower())

    def _generate_markdown(self, findings: List[Dict[str, Any]]) -> str:
        """Render and save the premium Markdown report."""
        env = Environment(loader=BaseLoader())
        template = env.from_string(_MARKDOWN_TEMPLATE)

        output = template.render(
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            target=self.target,
            findings=findings,
            critical_count=self._count(findings, "critical"),
            high_count=self._count(findings, "high"),
            medium_count=self._count(findings, "medium"),
            low_count=self._count(findings, "low"),
            info_count=self._count(findings, "info"),
        )

        report_path = self.workspace / "report.md"
        report_path.write_text(output, encoding="utf-8")
        self.logger.info(f"Markdown report saved → {report_path}")
        return str(report_path)

    def _generate_json(self, findings: List[Dict[str, Any]]) -> str:
        """Generate a machine-readable JSON summary and finding list."""
        report_data = {
            "version": "2.1",
            "date": datetime.now().isoformat(),
            "target": self.target,
            "total_findings": len(findings),
            "summary": {
                "critical": self._count(findings, "critical"),
                "high": self._count(findings, "high"),
                "medium": self._count(findings, "medium"),
                "low": self._count(findings, "low"),
                "info": self._count(findings, "info"),
            },
            "findings": findings,
        }

        report_path = self.workspace / "report.json"
        with report_path.open("w", encoding="utf-8") as f:
            json.dump(report_data, f, indent=4, default=str)

        self.logger.info(f"JSON report saved → {report_path}")
        return str(report_path)

    def _generate_csv(self, findings: List[Dict[str, Any]]) -> str:
        """Export findings to a spreadsheet-compatible CSV file."""
        report_path = self.workspace / "report.csv"
        fieldnames = ["title", "severity", "location", "description", "payload", "poc_lang", "poc", "validated"]

        with report_path.open("w", newline="", encoding="utf-8") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames, extrasaction='ignore')
            writer.writeheader()
            for finding in findings:
                # Ensure values are CSV safe
                row = {k: str(finding.get(k, "")) for k in fieldnames}
                writer.writerow(row)

        self.logger.info(f"CSV report saved → {report_path}")
        return str(report_path)
