"""
reporting/generator.py — Multi-Format Security Report Generator

Generates Markdown, JSON, and CSV reports enriched with:
  - CVSS v3.1 scores and vectors
  - Embedded Python PoC scripts
  - cURL one-liners
  - Root-cause analysis and remediation guidance
  - Diff-mode new/existing indicators
"""

import csv
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Union, Optional

from jinja2 import BaseLoader, Environment


_MARKDOWN_TEMPLATE = """\
# 🛡️ BBH-AI Security Assessment Report
> **Target:** `{{ target }}`
> **Generated:** {{ date }}
> **TCI Score:** {{ tci_score }}/100 ({{ tci_band }})
> **Status:** Scan Complete

---

## 📊 Executive Summary

| Severity | Count | CVSS Range | Impact |
|----------|-------|------------|--------|
| 🔴 **Critical** | {{ counts.critical }} | 9.0–10.0 | Immediate action required |
| 🟠 **High**     | {{ counts.high }}     | 7.0–8.9  | Significant security risk |
| 🟡 **Medium**   | {{ counts.medium }}   | 4.0–6.9  | Moderate security risk |
| 🟢 **Low**      | {{ counts.low }}      | 0.1–3.9  | Low security risk |
| ℹ️ **Info**    | {{ counts.info }}     | 0.0      | Informational |
| **Total**       | **{{ findings|length }}** | | |

---

## 🔍 Tactical Findings

{% for f in findings %}
### {{ loop.index }}. {{ f.title }}{% if f.is_new is defined and f.is_new %} ✨ **(NEW)**{% endif %}

| Attribute | Detail |
|-----------|--------|
| **Severity**   | {{ f.severity | upper }} |
| **CVSS Score** | {{ f.cvss_score }} |
| **CVSS Vector**| `{{ f.cvss_vector }}` |
| **Location**   | `{{ f.location }}` |
| **Validated**  | {{ "✅ Confirmed" if f.validated else "⚠️ Unvalidated" }} |

#### 📝 Description
{{ f.description }}

#### 🔎 Root Cause
{{ f.root_cause }}

#### 💥 Impact
{{ f.impact }}

{% if f.payload %}
#### 💉 Payload
```
{{ f.payload }}
```
{% endif %}

{% if f.poc_curl %}
#### 🖥️ cURL PoC
```bash
{{ f.poc_curl }}
```
{% endif %}

{% if f.poc_python %}
#### 🐍 Python PoC
```python
{{ f.poc_python }}
```
{% endif %}

#### 🔧 Remediation
{{ f.remediation }}

---
{% endfor %}

*Generated by BBH-AI v2.0 — Autonomous Bug Bounty Engine*
"""


class ReportGenerator:
    """Generates professional security reports in Markdown, JSON, and CSV formats."""

    def __init__(
        self,
        config: Dict[str, Any],
        workspace: Union[str, Path],
        target: str = "Unknown",
    ):
        self.config = config
        self.workspace = Path(workspace)
        self.workspace.mkdir(parents=True, exist_ok=True)
        self.target = target
        self.logger = logging.getLogger(__name__)

    def generate(
        self,
        findings: List[Dict[str, Any]],
        tci: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, str]:
        """Generate all configured report formats and return their file paths."""
        # Single O(n) pass for all severity counts
        counts = self._count_all(findings)
        tci = tci or {"score": 0, "band": "UNKNOWN"}

        report_paths: Dict[str, str] = {}
        formats: List[str] = self.config.get("reporting", {}).get(
            "formats", ["markdown", "json"]
        )

        if "markdown" in formats:
            report_paths["markdown"] = self._generate_markdown(findings, counts, tci)
        if "json" in formats:
            report_paths["json"] = self._generate_json(findings, counts, tci)
        if "csv" in formats:
            report_paths["csv"] = self._generate_csv(findings)

        return report_paths

    # ── Helpers ───────────────────────────────────────────────────────────────
    @staticmethod
    def _count_all(findings: List[Dict[str, Any]]) -> Dict[str, int]:
        """Compute all severity counts in a single O(n) pass."""
        counts: Dict[str, int] = {
            "critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0,
        }
        for f in findings:
            sev = str(f.get("severity", "info")).lower()
            if sev in counts:
                counts[sev] += 1
        return counts

    def _generate_markdown(
        self,
        findings: List[Dict[str, Any]],
        counts: Dict[str, int],
        tci: Dict[str, Any],
    ) -> str:
        env = Environment(loader=BaseLoader())
        template = env.from_string(_MARKDOWN_TEMPLATE)
        output = template.render(
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            target=self.target,
            findings=findings,
            counts=counts,
            tci_score=tci.get("score", 0),
            tci_band=tci.get("band", "UNKNOWN"),
        )
        report_path = self.workspace / "report.md"
        report_path.write_text(output, encoding="utf-8")
        self.logger.info(f"Markdown report saved → {report_path}")
        return str(report_path)

    def _generate_json(
        self,
        findings: List[Dict[str, Any]],
        counts: Dict[str, int],
        tci: Dict[str, Any],
    ) -> str:
        report_data = {
            "version":        "2.0",
            "date":           datetime.now().isoformat(),
            "target":         self.target,
            "tci":            tci,
            "total_findings": len(findings),
            "summary":        counts,
            "findings":       findings,
        }
        report_path = self.workspace / "report.json"
        with report_path.open("w", encoding="utf-8") as f:
            json.dump(report_data, f, indent=4, default=str)
        self.logger.info(f"JSON report saved → {report_path}")
        return str(report_path)

    def _generate_csv(self, findings: List[Dict[str, Any]]) -> str:
        report_path = self.workspace / "report.csv"
        fieldnames = [
            "title", "severity", "cvss_score", "cvss_vector",
            "location", "description", "root_cause", "impact",
            "payload", "poc_curl", "remediation", "validated",
        ]
        with report_path.open("w", newline="", encoding="utf-8") as csvfile:
            writer = csv.DictWriter(
                csvfile, fieldnames=fieldnames, extrasaction='ignore'
            )
            writer.writeheader()
            for finding in findings:
                row = {k: str(finding.get(k, "")) for k in fieldnames}
                writer.writerow(row)
        self.logger.info(f"CSV report saved → {report_path}")
        return str(report_path)


