"""
ci/notifier.py — Sends scan results to Slack and creates GitHub Issues.
Called automatically by Orchestrator after a scan completes when CI mode is active.
"""

import json
import logging
from dataclasses import dataclass

import requests

logger = logging.getLogger(__name__)


@dataclass
class NotificationPayload:
    target: str
    total: int
    critical: int
    high: int
    medium: int
    low: int
    report_path: str
    exit_code: int


class CINotifier:
    """Posts scan summaries to Slack and/or opens GitHub Issues for critical findings."""

    def __init__(self, config: dict):
        self.ci_cfg = config.get('ci', {})
        self.slack_webhook = self.ci_cfg.get('slack_webhook', '')
        self.github_token = self.ci_cfg.get('github_token', '')
        self.github_repo = self.ci_cfg.get('github_repo', '')   # e.g. "org/repo"

    def notify(self, payload: NotificationPayload) -> None:
        """Dispatch all configured notification channels."""
        if self.slack_webhook and self.slack_webhook.startswith('https://'):
            self._notify_slack(payload)
        if self.github_token and self.github_repo:
            self._notify_github(payload)

    # ── Slack ─────────────────────────────────────────────────────────────────
    def _notify_slack(self, p: NotificationPayload) -> None:
        severity_icon = "🔴" if p.critical else ("🟠" if p.high else "🟡" if p.medium else "🟢")
        text = (
            f"{severity_icon} *BBH-AI Scan Complete* — `{p.target}`\n"
            f"*Findings:* {p.total} total "
            f"({p.critical} critical, {p.high} high, {p.medium} medium, {p.low} low)\n"
            f"*Report:* `{p.report_path}`\n"
            f"*Exit code:* `{p.exit_code}`"
        )
        body = {
            "text": text,
            "blocks": [
                {"type": "section", "text": {"type": "mrkdwn", "text": text}}
            ],
        }
        try:
            resp = requests.post(self.slack_webhook, json=body, timeout=10)
            resp.raise_for_status()
            logger.info("Slack notification sent.")
        except Exception as e:
            logger.warning(f"Slack notification failed: {e}")

    # ── GitHub Issues ─────────────────────────────────────────────────────────
    def _notify_github(self, p: NotificationPayload) -> None:
        if not p.critical and not p.high:
            return   # Only open issues for critical/high findings
        title = f"[BBH-AI] {p.critical} critical / {p.high} high findings on {p.target}"
        body = (
            f"## BBH-AI Automated Scan Results\n\n"
            f"| Severity | Count |\n|----------|-------|\n"
            f"| 🔴 Critical | {p.critical} |\n"
            f"| 🟠 High | {p.high} |\n"
            f"| 🟡 Medium | {p.medium} |\n"
            f"| 🟢 Low | {p.low} |\n\n"
            f"**Target:** `{p.target}`\n"
            f"**Report:** `{p.report_path}`\n\n"
            f"_Auto-generated by BBH-AI_"
        )
        url = f"https://api.github.com/repos/{self.github_repo}/issues"
        headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github+json",
        }
        try:
            resp = requests.post(url, headers=headers, json={"title": title, "body": body}, timeout=15)
            resp.raise_for_status()
            issue_url = resp.json().get('html_url', '')
            logger.info(f"GitHub Issue opened: {issue_url}")
        except Exception as e:
            logger.warning(f"GitHub Issue creation failed: {e}")
