"""
validation/poc_generator.py — Automated Proof-of-Concept Generator

Produces two artifact types for every confirmed finding:
  1. A standalone, executable Python script using `requests`
  2. A copy-pasteable cURL command

Also provides payload mutation for double-confirmation before a PoC is
attached to a finding.
"""

import urllib.parse
from typing import Any, Dict


class PoCGenerator:
    """
    Generates reproducible PoC artifacts and mutates payloads to independently
    confirm vulnerabilities before they are included in reports.
    """

    _MUTATIONS = [
        # URL encoding
        lambda p: urllib.parse.quote(p, safe=''),
        # Double URL encoding
        lambda p: urllib.parse.quote(urllib.parse.quote(p, safe=''), safe=''),
        # Case variant (simple toggle for letter-only payloads)
        lambda p: p.swapcase(),
        # Append common comment bypass
        lambda p: p + "//",
        # HTML entity encoding for <
        lambda p: p.replace("<", "&#60;").replace(">", "&#62;"),
    ]

    # ── Public API ────────────────────────────────────────────────────────────
    def generate_python_poc(self, finding: Dict[str, Any]) -> str:
        """Return a self-contained Python PoC script for the given finding."""
        title    = finding.get('title', 'Security Finding')
        location = finding.get('location', 'http://target/')
        payload  = finding.get('payload', '')
        method   = finding.get('method', 'GET').upper()

        if method == 'POST':
            return self._python_post_poc(title, location, payload)
        return self._python_get_poc(title, location, payload)

    def generate_curl_poc(self, finding: Dict[str, Any]) -> str:
        """Return a one-liner cURL command for the given finding."""
        location = finding.get('location', 'http://target/')
        payload  = finding.get('payload', '')
        method   = finding.get('method', 'GET').upper()
        encoded  = urllib.parse.quote(payload, safe='')

        if method == 'POST':
            return (
                f"curl -sk -X POST"
                f" -d 'param={encoded}'"
                f" '{location}'"
                f" -w '\\n[HTTP %{{http_code}}]'"
            )
        return (
            f"curl -sk -G"
            f" --data-urlencode 'inject={payload}'"
            f" '{location}'"
            f" -w '\\n[HTTP %{{http_code}}]'"
        )

    def mutate_payload(self, payload: str) -> str:
        """
        Return the first non-identical mutation of `payload` for
        double-confirmation testing.
        """
        for mutator in self._MUTATIONS:
            try:
                mutated = mutator(payload)
                if mutated and mutated != payload:
                    return mutated
            except Exception:
                continue
        return payload + "//"  # fallback

    # ── Python PoC templates ──────────────────────────────────────────────────
    @staticmethod
    def _python_get_poc(title: str, location: str, payload: str) -> str:
        return f'''\
#!/usr/bin/env python3
"""
PoC: {title}
Target: {location}
Method: GET
Generated by BBH-AI — reproduce before disclosure.
"""
import sys
import requests

TARGET  = {location!r}
PAYLOAD = {payload!r}


def exploit(url: str = TARGET) -> bool:
    """Send the exploit payload and confirm vulnerability."""
    try:
        resp = requests.get(
            url,
            params={{"inject": PAYLOAD}},
            timeout=15,
            allow_redirects=False,
            verify=False,
        )
        confirmed = PAYLOAD in resp.text or resp.status_code in (500, 200)
        if confirmed:
            print(f"[+] CONFIRMED vulnerable! Status: {{resp.status_code}}")
            print(f"    URL    : {{resp.url}}")
            print(f"    Length : {{len(resp.text)}} bytes")
        else:
            print(f"[-] NOT confirmed (Status {{resp.status_code}})")
        return confirmed
    except requests.RequestException as exc:
        print(f"[!] Request failed: {{exc}}")
        sys.exit(1)


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else TARGET
    sys.exit(0 if exploit(target) else 2)
'''

    @staticmethod
    def _python_post_poc(title: str, location: str, payload: str) -> str:
        return f'''\
#!/usr/bin/env python3
"""
PoC: {title}
Target: {location}
Method: POST
Generated by BBH-AI — reproduce before disclosure.
"""
import sys
import requests

TARGET  = {location!r}
PAYLOAD = {payload!r}


def exploit(url: str = TARGET) -> bool:
    """Send the exploit payload via POST and confirm vulnerability."""
    try:
        resp = requests.post(
            url,
            data={{"param": PAYLOAD}},
            timeout=15,
            allow_redirects=False,
            verify=False,
        )
        confirmed = PAYLOAD in resp.text or resp.status_code in (200, 302, 500)
        if confirmed:
            print(f"[+] CONFIRMED vulnerable! Status: {{resp.status_code}}")
            print(f"    URL    : {{url}}")
            print(f"    Length : {{len(resp.text)}} bytes")
        else:
            print(f"[-] NOT confirmed (Status {{resp.status_code}})")
        return confirmed
    except requests.RequestException as exc:
        print(f"[!] Request failed: {{exc}}")
        sys.exit(1)


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else TARGET
    sys.exit(0 if exploit(target) else 2)
'''
